#!/bin/bash

#
# Set some variables according to OS
#

for i in $NODE_LABELS
do
	echo $i
	if [ $i = "ubuntu10.04" ]
	then
		echo "Ubuntu 10.04 OS"
		OS_TYPE="linux"
		OS_SPEC="linux=1 ubuntu=1"
		CPU_BUS="64bits=1"
		MAKE_PATH="make"
		INSTALL_DIR=/tmp/ci
	fi
	
	if [ $i = "solaris10" ]
	then
		echo "Solaris 10 OS"
		OS_TYPE="solaris"
		OS_SPEC="_solaris=1"
		MAKE_PATH="/usr/local/bin/make"
		INSTALL_DIR=/tmp/ci
	fi

	if [ $i = "Windows_VC9" ]
	then
		echo "Windows VC9"
		OS_TYPE="Windows"
		OS_SPEC="Windows"
		MAKE_PATH="devenv"
		INSTALL_DIR=/cygdrive/c/tango_src/ci
	fi
	
	if [ $i = "redhate5" ]
	then
		echo "redhate 5 OS"
		OS_SPEC="linux=1"
		CPU_BUS="64bits=1"
		MAKE_PATH="make"
		INSTALL_DIR=/tmp/ci
	fi
done

#
# Set library type
#

if [ $OS_TYPE = "Windows" ]
then
	if [ $LIBTYPE = "shared" ]
	then
		LIBNAME=tango_dll
		OUTFILEBASE="devenv_dll"
	else
		LIBNAME=tango_static
		OUTFILEBASE="devenv_static"
	fi
else
	if [ $LIBTYPE = "shared" ]
	then
		LIBNAME=libtango.so
	else
		LIBNAME=libtango.a
	fi
fi

#
# Set debug type
#

if [ $OS_TYPE = "Windows" ]
then
	if [ $DEBUGMODE = "debug" ]
	then
		DEBUG_MODE="debug"
		OUTFILE=$OUTFILEBASE"_debug"
	else
		DEBUG_MODE="release"
		OUTFILE=$OUTFILEBASE"_release"
	fi
else
	if [ $DEBUGMODE = "debug" ]
	then
		DEBUG_MODE="debug=1"
	fi
fi

#
# Build library
#

if [ $OS_TYPE = "Windows" ]
then
	MAKE_CMD="$MAKE_PATH /build $DEBUG_MODE /project $LIBNAME /out $OUTFILE winnt_lib.sln"
	export PATH=$PATH:/cygdrive/c/Program\ Files/Microsoft\ Visual\ Studio\ 9.0/Common7/IDE
	echo $PATH
	export PREFIX=$INSTALL_DIR
	cd NextRelease/win32/tango_vc9
	/bin/rm -f $OUTFILE
else
	MAKE_CMD="$MAKE_PATH prefix=$INSTALL_DIR $OS_SPEC $CPU_BUS $DEBUG_MODE $LIBNAME install_include install_link"

	cd NextRelease
fi

echo $MAKE_CMD
$MAKE_CMD
RET=$?

#
# On Windows, cat the output file and if compilation is OK, also copy include files
#

if [ $OS_TYPE = "Windows" ]
then
	/bin/cat $OUTFILE
	if [ $RET = 0 ]
	then
		cd ../..
		mkdir -p $INSTALL_DIR/win32/include
		mkdir -p $INSTALL_DIR/win32/include/idl
		cp client/*.h $INSTALL_DIR/win32/include
		cp server/*.h $INSTALL_DIR/win32/include
		cp server/idl/*.h $INSTALL_DIR/win32/include/idl
	fi
fi

if [ $RET != 0 ]
then
	exit -1
fi
