#!/bin/bash

#INSTALL_DIR=/segfs/tango/tmp/ci
INSTALL_DIR=/tmp/ci

for i in $NODE_LABELS
do
	echo $i
	if [ $i = "ubuntu10.04" ]
	then
		echo "Ubuntu 10.04 OS"
		OS_SPEC="linux=1 ubuntu=1"
		CPU_BUS="64bits=1"
		MAKE_PATH="make"
	fi
	
	if [ $i = "solaris10" ]
	then
		echo "Solaris 10 OS"
		OS_SPEC="_solaris=1"
		MAKE_PATH="/usr/local/bin/make"
	fi
	
	if [ $i = "redhate5" ]
	then
		echo "redhate 5 OS"
		OS_SPEC="linux=1"
		CPU_BUS="64bits=1"
		MAKE_PATH="make"
	fi
done


if [ $LibType = "shared" ]
then
	LIBNAME=libtango.so
else
	LIBNAME=libtango.a
fi

if [ $DebugMode = "debug" ]
then
	DEBUG_MODE="debug=1"
fi

MAKE_CMD="$MAKE_PATH prefix=$INSTALL_DIR $OS_SPEC $CPU_BUS $DEBUG_MODE $LIBNAME install_include install_link"

cd NextRelease
echo $MAKE_CMD
$MAKE_CMD
